# -*- coding: utf-8 -*-
"""MakineProjesiKod.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OxIAdS6ApANn64PI8kyqMyjtLF98Erh6

# Veri Odaklı Tarımsal Yatırım Danışmanlığı ve Karar Destek Sistemi

**Ders:** Makine Öğrenmesi (Machine Learning)  
**Geliştirenler:** Elif Bilge Güleç & Ümmü Habibe Yüze  
**Kurum:** İstanbul Sabahattin Zaim Üniversitesi - Bilgisayar Mühendisliği  

---

### Proje Senaryosu ve Amacı
Bu proje, geleneksel bir bitki tahmin modelinin ötesine geçerek bir **Yatırım Danışmanlığı** senaryosu üzerine kurgulanmıştır.

**Senaryo:** Bir yatırımcının veya çiftçinin elindeki arazinin toprak (N, P, K, pH) ve iklim (Sıcaklık, Nem, Yağış) verileri analiz edilerek; o arazi için risk oranı en düşük ve başarı ihtimali en yüksek bitki türü belirlenir.

**Neden Bu Senaryo?**
*   **Stratejik Karar Verme:** Sadece tahmin üretmek yerine, tarımsal yatırımların doğruluğunu bilimsel verilerle kanıtlamak.
*   **Güvenilirlik:** Modelin kararlarını "Kara Kutu" (Black Box) olmaktan çıkarıp, **SHAP** analizi ile neden bu öneriyi verdiğini yatırımcıya açıklamak.
*   **Hassas Tarım (Precision Agriculture):** Kaynakların (su, gübre, zaman) en verimli şekilde kullanılmasını sağlamak.

---
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

import os
import pandas as pd

# Kodun hata vermemesi için klasördeki ilk .zip dosyasını otomatik bulan dinamik bir yapı kuruyoruz.
zip_dosyalari = [f for f in os.listdir('.') if f.endswith('.zip')]

if zip_dosyalari:
    secilen_zip = zip_dosyalari[0]
    print(f"Veri seti zip dosyası bulundu: {secilen_zip}. Seçiliyor...")
    os.system(f'unzip -o "{secilen_zip}"')
else:
    print("Klasörde zip dosyası bulunamadı, doğrudan .csv aranıyor...")

# Klasöre çıkan veya zaten orada olan csv dosyasını okuyoruz
df = pd.read_csv('Crop_recommendation.csv')
print("Veri seti başarıyla yüklendi. Satır ve Sütun Sayısı:", df.shape)

df = pd.read_csv('Crop_recommendation.csv')
df.head()

df = pd.read_csv('Crop_recommendation.csv')
df.head()

#AYKIRI DEĞERLERİN BULUNMASI
plt.figure(figsize=(15, 8))
sns.boxplot(data=df.drop('label', axis=1))
plt.title("Değişkenlerin Dağılımı ve Aykırı Değerler")
plt.xticks(rotation=45)
plt.show()

#GÖREV 1 (AYKIRI DEĞERLERİN TEMİZLENMESİ)

numeric_df = df.select_dtypes(include=['number'])

Q1 = numeric_df.quantile(0.25)
Q3 = numeric_df.quantile(0.75)
IQR = Q3 - Q1

df_temiz = df[~((numeric_df < (Q1 - 1.5 * IQR)) | (numeric_df > (Q3 + 1.5 * IQR))).any(axis=1)]

print(f"Eski veri: {len(df)} | Yeni veri: {len(df_temiz)}")

plt.figure(figsize=(15, 8))
sns.boxplot(data=df_temiz.drop('label', axis=1))
plt.title("Temizlik Sonrası Değişkenlerin Dağılımı")
plt.xticks(rotation=45)
plt.show()

# GÖREV 2, NORMALIZASYON (Normalizasyon veri sızıntısını önlemek için Görev 3'e taşındı)

# Veriyi doğrudan kopyalıyoruz, normalleştirme işlemini split sonrasına bırakıyoruz
df_normalize = df_temiz.copy()

print("Veriler ham haliyle bir sonraki adıma aktarıldı:")
display(df_normalize.head())

#3 Farklı Özellik Seçim Yönteminden İlki

plt.figure(figsize=(10, 6))
# Sadece sayısal sütunların birbirine benzerliğine bakıyoruz
sns.heatmap(df_normalize.drop('label', axis=1).corr(), annot=True, cmap='coolwarm')
plt.title("Hangi özellikler birbirine benziyor?")
plt.show()

"""### 🔍 Korelasyon Analizi Bulguları
Bu ısı haritası, toprak ve iklim değişkenleri arasındaki ilişkileri ortaya koymaktadır:
*   **En Güçlü Pozitif İlişki:** Azot (N) ve Potasyum (K) arasında görülmektedir (0.34). Bu, yatırım planlamasında toprak besin elementlerinin dengeli dağılımını takip etmek gerektiğini gösterir.
*   **En Güçlü Negatif İlişki:** Fosfor (P) ve Nem (humidity) arasında (-0.47) bir ilişki saptanmıştır.
*   **Bağımsızlık:** pH ve sıcaklık değerlerinin diğer değişkenlerle düşük korelasyona sahip olması, bu özelliklerin modelde "ayırt edici" (unique) bilgiler sunacağını kanıtlar.
"""

#2.YÖNTEM, Random Forest Feature Importance
from sklearn.ensemble import RandomForestClassifier

# X = Bilgiler (N, P, K...), y = Hedef (Mahsul ismi)
X = df_normalize.drop('label', axis=1)
y = df_normalize['label']

model = RandomForestClassifier()
model.fit(X, y)

# Puanları görselleştirelim
onemli_ozellikler = pd.Series(model.feature_importances_, index=X.columns)
onemli_ozellikler.nlargest(7).plot(kind='barh', color='teal')
plt.title("Yapay Zekaya Göre En Önemli 7 Özellik")
plt.show()

#3. YÖNTEM

from sklearn.feature_selection import SelectKBest, f_classif
# Yöntemi hazırlayalım (f_classif istatistiksel bir testtir)
# k='all' diyerek hepsine puan vermesini istiyoruz
selector = SelectKBest(score_func=f_classif, k='all')
selector.fit(X, y)

# Puanları bir tabloya döküp görelim
skorlar = pd.DataFrame({
    'Özellik': X.columns,
    'İstatistiksel Skor': selector.scores_
})

# Büyükten küçüğe sıralayıp görelim
print("--- Yöntem 3: SelectKBest (İstatistiksel) Puanları ---")
display(skorlar.sort_values(by='İstatistiksel Skor', ascending=False))

"""📌 Karar Notu: Özellik Seçimi Sonucu
Analiz Sonucu: Yapılan 3 farklı testte (Korelasyon, RF, SelectKBest) humidity, rainfall ve K en güçlü belirleyiciler çıkarken; ph ve temperature en düşük skorları almıştır.

Mühendislik Kararı: İstatistiksel skorları düşük olsa da, ph ve temperature verileri tarımsal üretimde "hayati" öneme sahip olduğu için bilgi kaybını önlemek adına veri setinden elenmemiştir.

Strateji: Modelleme aşamasına tüm özellikler (7/7) korunarak geçilmiştir.
"""

# GÖREV 3: VERİ BÖLME VE DOĞRU NORMALİZASYON (KUSURSUZ MİMARİ - STRATIFY HATASI DÜZELTİLDİ)
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# 1. Ana veriden tertemiz X ve y alıyoruz
X_ham = df_temiz.drop(columns=['label']).reset_index(drop=True)
y_ham = df_temiz['label'].reset_index(drop=True)

# 2. İLK BÖLÜNME: %70 Train, %30 Geçici (Temp)
# Burada stratify olarak y_ham kullanıyoruz
X_train_raw, X_temp_raw, y_train, y_temp = train_test_split(
    X_ham, y_ham, test_size=0.30, random_state=42, stratify=y_ham
)

# 3. İKİNCİ BÖLÜNME: %30'luk Geçici seti yarı yarıya bölüyoruz (%15 Val, %15 Test)
# KRİTİK DÜZELTME: stratify parametresine artık 'y_temp' vermeliyiz, en baştaki 'y_ham'ı değil!
X_val_raw, X_test_raw, y_val, y_test = train_test_split(
    X_temp_raw, y_temp, test_size=0.50, random_state=42, stratify=y_temp
)

# 4. AKADEMİK OLARAK DOĞRU ÖLÇEKLENDİRME (DATA LEAKAGE ENGELLENDİ)
scaler = MinMaxScaler()

# Sadece Train setiyle fit_transform yapıyoruz
X_train = scaler.fit_transform(X_train_raw)

# Val ve Test setlerini sadece transform ediyoruz (Sızıntı bitti!)
X_val = scaler.transform(X_val_raw)
X_test = scaler.transform(X_test_raw)

print("Veri bölme ve güvenli normalizasyon başarıyla tamamlandı! 🎉")
print("Eğitim (Train) seti boyutu       :", X_train.shape[0])
print("Doğrulama (Validation) seti boyutu:", X_val.shape[0])
print("Test seti boyutu                 :", X_test.shape[0])

#GÖREV 3

# 1. Model: Random Forest (Rastgele Orman)
from sklearn.ensemble import RandomForestClassifier
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train, y_train)

# 2. Model: SVM (Destek Vektör Makineleri)
from sklearn.svm import SVC
svm_model = SVC(probability=True, random_state=42)
svm_model.fit(X_train, y_train)

# 3. Model: Naive Bayes
from sklearn.naive_bayes import GaussianNB
nb_model = GaussianNB()
nb_model.fit(X_train, y_train);

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Tahminleri hem Doğrulama hem de Test seti için alıyoruz
rf_pred_val = rf_model.predict(X_val)
rf_pred_test = rf_model.predict(X_test)

svm_pred_val = svm_model.predict(X_val)
svm_pred_test = svm_model.predict(X_test)

nb_pred_val = nb_model.predict(X_val)
nb_pred_test = nb_model.predict(X_test)

# Grafikleme fonksiyonu (Aynı anda iki seti de çizecek şekilde güncelledik)
def c_matris_ikili_ciz(y_val_true, y_val_pred, y_test_true, y_test_pred, model_adi):
    fig, ax = plt.subplots(1, 2, figsize=(16, 6))

    # Doğrulama Seti Matrisi
    cm_val = confusion_matrix(y_val_true, y_val_pred)
    disp_val = ConfusionMatrixDisplay(confusion_matrix=cm_val)
    disp_val.plot(cmap='Greens', ax=ax[0])
    ax[0].set_title(f"{model_adi} - Doğrulama Seti")

    # Test Seti Matrisi
    cm_test = confusion_matrix(y_test_true, y_test_pred)
    disp_test = ConfusionMatrixDisplay(confusion_matrix=cm_test)
    disp_test.plot(cmap='Blues', ax=ax[1])
    ax[1].set_title(f"{model_adi} - Test Seti")

    plt.suptitle(f"--- {model_adi} Karışıklık Matrisleri ---", fontsize=16, y=1.02)
    plt.show()

# 3 Model için de grafikleri ekrana basalım
c_matris_ikili_ikili_ciz = c_matris_ikili_ciz # Kısa isim referansı
c_matris_ikili_ciz(y_val, rf_pred_val, y_test, rf_pred_test, "Random Forest")
c_matris_ikili_ciz(y_val, svm_pred_val, y_test, svm_pred_test, "SVM")
c_matris_ikili_ciz(y_val, nb_pred_val, y_test, nb_pred_test, "Naive Bayes")

"""📝 Görev 3: Modelleme (Güncellenmiş Özet Notlar)
Veri Bölme: Veri seti, modelin ezberlemesini (overfitting) kesin olarak önlemek ve hiperparametre optimizasyonunu güvenli bir şekilde gerçekleştirmek amacıyla modern veri bilimi standartlarına uygun olarak %70 Eğitim (Train), %15 Doğrulama (Validation) ve %15 Test seti olacak şekilde 3'e ayrılmıştır. stratify parametresi kullanılarak tüm alt setlerdeki 20 farklı bitki sınıfının dengeli dağılımı korunmuştur.

Algoritma Seçimi: Proje isterlerine tam uyum sağlayacak şekilde, farklı matematiksel altyapılara sahip 3 güçlü makine öğrenmesi modeli seçilmiştir: Random Forest (Topluluk Öğrenme), SVM (Geometrik/Vektör Tabanlı Sınıflandırma) ve Naive Bayes (Olasılık Tabanlı Sınıflandırma).

Model Eğitimi: Modeller; toprak (N, P, K, pH) ve iklim (Sıcaklık, Nem, Yağış) değişkenlerini girdi olarak alıp, "Yatırım Danışmanlığı" senaryomuz altındaki en optimize bitki türünü (label) tahmin etmek üzere eğitilmiştir.

Performans Ölçümü ve Doğrulama: Modellerin gerçek dünya verilerindeki başarısını simüle etmek amacıyla, performans analizi hem hiperparametre kararlarının alındığı Doğrulama (Validation) seti üzerinde hem de modelin daha önce kesinlikle karşılaşmadığı nihai Test seti üzerinde ayrı ayrı yürütülmüştür.

Çift Yönlü Karışıklık Matrisi (Confusion Matrix) Analizi: Modellerin sınıf bazındaki başarılarını ve birbirine yakın iklim/toprak istekleri olan mahsulleri (örneğin mısır ve pirinç) ne oranda karıştırdığını gözlemlemek adına, hem Doğrulama hem de Test setleri için ikili karışıklık matrisleri çizdirilerek karşılaştırmalı analiz yapılmıştır.
"""

# GÖREV 4: MODEL DEĞERLENDİRME METRİKLERİ
from sklearn.metrics import accuracy_score, classification_report

def metrikleri_yazdir_v3(model, X_train, y_train, X_val, y_val, X_test, y_test, model_adi):
    # Tüm setler için tahminlerin üretilmesi
    train_pred = model.predict(X_train)
    val_pred = model.predict(X_val)
    test_pred = model.predict(X_test)

    print(f"\n==================== {model_adi} Performans Sonuçları ====================")
    # Hocanın istediği 3'lü Accuracy listesi
    print(f"Eğitim Doğruluğu (Train Accuracy)      : {accuracy_score(y_train, train_pred):.4f}")
    print(f"Doğrulama Doğruluğu (Val Accuracy)     : {accuracy_score(y_val, val_pred):.4f}")
    print(f"Test Doğruluğu (Test Accuracy)         : {accuracy_score(y_test, test_pred):.4f}")

    # 1. Eğitim Seti Detaylı Raporu
    print(f"\n[Eğitim (Train) Seti Detaylı Raporu]:")
    print(classification_report(y_train, train_pred))

    # 2. Detaylı raporlar (Precision, Recall, F1-Score)
    print(f"\n[Doğrulama (Validation) Seti Detaylı Raporu]:")
    print(classification_report(y_val, val_pred))

    # 3. Nihai Test Seti Detaylı Raporu
    print(f"\n[Nihai Test Seti Detaylı Raporu]:")
    print(classification_report(y_test, test_pred))

# 3 Modeli de yeni 3'lü sistemimizle test edelim
metrikleri_yazdir_v3(rf_model, X_train, y_train, X_val, y_val, X_test, y_test, "Random Forest")
metrikleri_yazdir_v3(svm_model, X_train, y_train, X_val, y_val, X_test, y_test, "Support Vector Machine")
metrikleri_yazdir_v3(nb_model, X_train, y_train, X_val, y_val, X_test, y_test, "Naive Bayes")

# GÖREV 4: EĞİTİM VE DOĞRULAMA SETLERİ İÇİN ROC ANALİZİ
from sklearn.metrics import roc_curve, auc
from sklearn.preprocessing import label_binarize
import numpy as np
import matplotlib.pyplot as plt

# 1. Gerçek etiketleri bilgisayarın anlayacağı 0-1 formatına getiriyoruz
y_train_bin = label_binarize(y_train, classes=rf_model.classes_)
y_val_bin = label_binarize(y_val, classes=rf_model.classes_)

# 2. En başarılı model olan Random Forest'ın tahmin olasılık skorlarını alıyoruz
rf_score_train = rf_model.predict_proba(X_train)
rf_score_val = rf_model.predict_proba(X_val)

# 3. Eğitim Seti için Genel (Macro-average) ROC Değerlerini Hesaplama
fpr_train, tpr_train, _ = roc_curve(y_train_bin.ravel(), rf_score_train.ravel())
roc_auc_train = auc(fpr_train, tpr_train)

# 4. Doğrulama Seti için Genel (Macro-average) ROC Değerlerini Hesaplama
fpr_val, tpr_val, _ = roc_curve(y_val_bin.ravel(), rf_score_val.ravel())
roc_auc_val = auc(fpr_val, tpr_val)

# 5. Görselleştirme: İki Eğrinin Karşılaştırmalı Grafiği
plt.figure(figsize=(8, 6))
plt.plot(fpr_train, tpr_train, label=f'Eğitim Seti Genel ROC (AUC = {roc_auc_train:.4f})', color='blue', lw=2)
plt.plot(fpr_val, tpr_val, label=f'Doğrulama Seti Genel ROC (AUC = {roc_auc_val:.4f})', color='orange', lw=2)

plt.plot([0, 1], [0, 1], 'k--', lw=1.5)
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('Yanlış Pozitif Oranı (False Positive Rate)')
plt.ylabel('Doğru Pozitif Oranı (True Positive Rate)')
plt.title('Random Forest - Eğitim vs Doğrulama Seti Karşılaştırmalı ROC Eğrisi')
plt.legend(loc="lower right")
plt.grid(True, alpha=0.3)
plt.show()

# GÖREV 4: EĞİTİM VS DOĞRULAMA SETİ RECALL (DUYARLILIK) ANALİZİ
from sklearn.metrics import recall_score
import pandas as pd
import matplotlib.pyplot as plt

# 1. Tahminleri Eğitim ve Doğrulama (Validation) setleri için alıyoruz
y_train_pred = rf_model.predict(X_train)
y_val_pred = rf_model.predict(X_val)

# 2. Her bitki türü (sınıf) için recall skorlarını bağımsız hesaplıyoruz
# (average=None parametresi her sınıfın kendi skorunu üretmesini sağlar)
recall_train = recall_score(y_train, y_train_pred, average=None)
recall_val = recall_score(y_val, y_val_pred, average=None)

# 3. Sonuçları görselleştirmek için DataFrame'e aktarıyoruz
recall_df = pd.DataFrame({
    'Bitki': rf_model.classes_,
    'Eğitim Seti': recall_train,
    'Doğrulama Seti': recall_val
})

# 4. Çubuk Grafik Çizimi
ax = recall_df.plot(x='Bitki', y=['Eğitim Seti', 'Doğrulama Seti'], kind='bar', figsize=(15, 6), color=['navy', 'orange'])
plt.title('Random Forest - Eğitim vs Doğrulama Seti Recall (Duyarlılık) Karşılaştırması', fontsize=14, pad=15)
plt.ylabel('Recall Skoru', fontsize=12)
plt.xlabel('Bitki Türleri', fontsize=12)
plt.ylim(0, 1.15)  # Lejantın barları kapatmaması için üst sınırı biraz esnettik
plt.xticks(rotation=45, ha='right')
plt.legend(loc='upper right')
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.show()

"""##Açıklanabilir Yapay Zeka (XAI) ve Güvenilirlik Analizi
Gerekçe:
Makine öğrenmesi modelleri (özellikle Random Forest) genellikle birer "kara kutu" (black-box) olarak çalışır; yani sonucu verir ama "neden" verdiğini söylemez. Agro-Invest projemizde, yatırımcıya sunduğumuz bitki önerisinin bilimsel dayanağını kanıtlamak ve modelin güvenilirliğini (reliability) doğrulamak amacıyla SHAP (SHapley Additive exPlanations) analizini kullanıyoruz. Bu analiz, modelin hangi özelliği (Nem, Potasyum vb.) ne kadar ağırlıkla dikkate aldığını şeffaflaştırır.
"""

# KARA KUTU MODELİ
import shap
import matplotlib.pyplot as plt

explainer = shap.TreeExplainer(rf_model)
shap_values = explainer.shap_values(X_test)

print("--- Agro-Invest: Model Karar Destek Kanıtları ---")
shap.summary_plot(shap_values, X_test, plot_type="bar", feature_names=X.columns)

#CANLIYA ALMA
import joblib

# Modeli ve Scaler'ı kaydediyoruz
joblib.dump(rf_model, 'agro_invest_model.pkl')
joblib.dump(scaler, 'scaler.pkl')
print("Model ve Ölçekleyici başarıyla paketlendi! ✅")

# Streamlit İçin Gerekli kütüphaneleri kuruyoruz
!pip install streamlit -q
!pip install pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import pandas as pd
# import streamlit as st
# import joblib
# import numpy as np
# 
# st.set_page_config(page_title="Agro-Invest", page_icon="🌱", layout="centered")
# 
# st.title("🌱 Akıllı Tarım Yatırım Paneli")
# st.markdown("""
# Bu panel, toprak ve iklim verilerinizi analiz ederek yatırım yapabileceğiniz **en karlı ve uygun mahsulü** önerir.
# """)
# 
# st.divider()
# 
# col1, col2 = st.columns(2)
# 
# with col1:
#     n = st.number_input("Azot (N) Miktarı", 0, 150, help="Topraktaki azot değeri")
#     p = st.number_input("Fosfor (P) Miktarı", 0, 150)
#     k = st.number_input("Potasyum (K) Miktarı", 0, 210)
#     temp = st.number_input("Sıcaklık (°C)", 5.0, 50.0)
# 
# with col2:
#     hum = st.number_input("Nem Oranı (%)", 10.0, 100.0)
#     ph = st.number_input("pH Değeri", 3.0, 10.0)
#     rain = st.number_input("Yağış Miktarı (mm)", 20.0, 300.0)
# 
# st.divider()
# 
# if st.button("Yatırım Analizini Başlat"):
# 
#     model = joblib.load('agro_invest_model.pkl')
#     scaler = joblib.load('scaler.pkl')
# 
#     # 1. Verileri bir sözlük (dictionary) olarak, veri setindeki orijinal isimlerle topluyoruz
#     input_dict = {
#         'N': [n],
#         'P': [p],
#         'K': [k],
#         'temperature': [temp],
#         'humidity': [hum],
#         'ph': [ph],
#         'rainfall': [rain]
#     }
# 
#     # 2. Sözlüğü DataFrame'e dönüştürüyoruz
#     inputs_df = pd.DataFrame(input_dict)
# 
#     # 3. Modelin eğitildiği sütun sırasını garanti altına almak için
#     orijinal_siralar = ['N', 'P', 'K', 'temperature', 'humidity', 'ph', 'rainfall']
#     inputs_df = inputs_df[orijinal_siralar]
# 
#     inputs_scaled = scaler.transform(inputs_df)
# 
#     tahmin = model.predict(inputs_scaled)
# 
#     st.balloons()
#     st.success(f"📈 Agro-Invest Stratejik Önerisi: **{tahmin[0].upper()}**")
#     st.info("Bu öneri, girilen veriler doğrultusunda makine öğrenmesi modelimiz tarafından en yüksek güvenilirlikle hesaplanmıştır.")

#Streamlit'i arkaplanda başlatıyoruz
get_ipython().system_raw('streamlit run app.py &')
print("Streamlit arka planda başarıyla tetiklendi! 🚀")

# Streamlit'e tünel açıyoruz
!npx localtunnel --port 8501